REGIOES_POR_ESTADO = {
    'acre': 'Norte',
    'alagoas': 'Nordeste',
    'amapá': 'Norte',
    'amazonas': 'Norte',
    'bahia': 'Nordeste',
    'ceará': 'Nordeste',
    'distrito federal': 'Centro-Oeste',
    'espírito santo': 'Sudeste',
    'goiás': 'Centro-Oeste',
    'maranhão': 'Nordeste',
    'mato grosso': 'Centro-Oeste',
    'mato grosso do sul': 'Centro-Oeste',
    'minas gerais': 'Sudeste',
    'pará': 'Norte',
    'paraíba': 'Nordeste',
    'paraná': 'Sul',
    'pernambuco': 'Nordeste',
    'piauí': 'Nordeste',
    'rio de janeiro': 'Sudeste',
    'rio grande do norte': 'Nordeste',
    'rio grande do sul': 'Sul',
    'rondônia': 'Norte',
    'roraima': 'Norte',
    'santa catarina': 'Sul',
    'são paulo': 'Sudeste',
    'sergipe': 'Nordeste',
    'tocantins': 'Norte'
}
